---
title: "p8105_hw1_mmu2108"
output: html_document
date: "2022-09-15"
---

```{r penguindata}
library(tidyverse)
data("penguins", package = "palmerpenguins")
```

# Problem 1

-   The dataset "penguins" has 8 variables detailing penguin species, island found, measurements of the penguin's bill, flipper, and body mass, sex, and year found.
-   There are `r nrow(penguins)` rows and `r ncol(penguins)` columns.
-   Mean flipper length is `r mean(penguins$flipper_length_mm, na.rm = TRUE)` mm.

```{r scatterplot}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
ggsave("q1_plot.pdf")
```

# Problem 2

```{r q2}
q2 =
  tibble(
    rand_samp = rnorm(n = 10),
    rand_samp_pos = rand_samp > 0,
    char_vect = character(length = 10),
    factor_vect = factor(rand_samp, levels = 1:3)
  )
  
  mean_rand_samp = mean(pull(q2, rand_samp))
  mean_rand_samp_pos = mean(pull(q2, rand_samp_pos))
  mean_char_vect = mean(pull(q2, char_vect))
  mean_factor_vect = mean(pull(q2, factor_vect))
```

```{r}
as.numeric(pull(q2, rand_samp_pos))
as.numeric(pull(q2, char_vect))
as.numeric(pull(q2, factor_vect))
```



